services:
  spark:
    version: 2.0.0-preview
    # git-commit: latest  # if not 'latest', provide a full commit SHA; e.g. d6dc12ef0146ae409834c78737c116050961f350
    # git-repository:  # optional; defaults to https://github.com/apache/spark
  hdfs:
    version: 2.7.2

provider: ec2

providers:
  ec2:
    key-name: ec2stonybrook
    identity-file: /Users/pingu/.ec2/ec2stonybrook.pem
    instance-type: m3.medium
    region: us-west-2
    ami: ami-7172b611   # Amazon Linux, us-west-2
    user: ec2-user
    # availability-zone: <name>
    # spot-price: <price>
    # vpc-id: <id>
    # subnet-id: <id>
    # placement-group: <name>
    tenancy: default  # default | dedicated
    ebs-optimized: no  # yes | no
    instance-initiated-shutdown-behavior: stop  # terminate | stop

launch:
  num-slaves: 4
  install-hdfs: True
  install-spark: True
