function [jobIds,cpu,ram,disk] = importResUsage(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [JOBIDS,CPU,RAM,DISK] = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   [JOBIDS,CPU,RAM,DISK] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [jobIds,cpu,ram,disk] = importfile('jobResusage.csv',1, 666798);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/01/30 19:06:19

%% Initialize variables.
delimiter = ',';
if nargin<=2
  startRow = 1;
  endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
  frewind(fileID);
  dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
  for col=1:length(dataArray)
    dataArray{col} = [dataArray{col};dataArrayBlock{col}];
  end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
jobIds = dataArray{:, 1};
cpu = dataArray{:, 2};
ram = dataArray{:, 3};
disk = dataArray{:, 4};


