function [timestamp,missinfo,jobIds,eventType,Username,schedulingClass,jobName,logicalJobName] = importJobEventFile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIMESTAMP,MISSINFO,JOBIDS,EVENTTYPE,USERNAME,SCHEDULINGCLASS,JOBNAME,LOGICALJOBNAME]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIMESTAMP,MISSINFO,JOBIDS,EVENTTYPE,USERNAME,SCHEDULINGCLASS,JOBNAME,LOGICALJOBNAME]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [timestamp,missinfo,jobIds,eventType,Username,schedulingClass,jobName,logicalJobName] = importfile('part-00001-of-00500.csv',1, 3099);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/01/30 15:01:11

%% Initialize variables.
delimiter = ',';
if nargin<=2
  startRow = 1;
  endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: double (%f)
%	column4: double (%f)
%   column5: text (%s)
%	column6: double (%f)
%   column7: text (%s)
%	column8: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%f%f%s%f%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
  frewind(fileID);
  dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
  for col=1:length(dataArray)
    dataArray{col} = [dataArray{col};dataArrayBlock{col}];
  end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
timestamp = dataArray{:, 1};
missinfo = dataArray{:, 2};
jobIds = dataArray{:, 3};
eventType = dataArray{:, 4};
Username = dataArray{:, 5};
schedulingClass = dataArray{:, 6};
jobName = dataArray{:, 7};
logicalJobName = dataArray{:, 8};


