function [timestamp,missinginfo,jobIds,taskIdInAJob,machineIds,eventType,usernames,schedulingClass,priorities,cpu,ram,disk,constraint] = importTaskEvents(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIMESTAMP,MISSINGINFO,JOBIDS,TASKIDINAJOB,MACHINEIDS,EVENTTYPE,USERNAMES,SCHEDULINGCLASS,PRIORITIES,CPU,RAM,DISK,CONSTRAINT]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIMESTAMP,MISSINGINFO,JOBIDS,TASKIDINAJOB,MACHINEIDS,EVENTTYPE,USERNAMES,SCHEDULINGCLASS,PRIORITIES,CPU,RAM,DISK,CONSTRAINT]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [timestamp,missinginfo,jobIds,taskIdInAJob,machineIds,eventType,usernames,schedulingClass,priorities,cpu,ram,disk,constraint] = importfile('part-00000-of-00500.csv',1, 450146);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/01/30 18:48:50

%% Initialize variables.
delimiter = ',';
if nargin<=2
  startRow = 1;
  endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: text (%s)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%s%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,0.0,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
  frewind(fileID);
  dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,0.0,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
  for col=1:length(dataArray)
    dataArray{col} = [dataArray{col};dataArrayBlock{col}];
  end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
timestamp = dataArray{:, 1};
missinginfo = dataArray{:, 2};
jobIds = dataArray{:, 3};
taskIdInAJob = dataArray{:, 4};
machineIds = dataArray{:, 5};
eventType = dataArray{:, 6};
usernames = dataArray{:, 7};
schedulingClass = dataArray{:, 8};
priorities = dataArray{:, 9};
cpu = dataArray{:, 10};
ram = dataArray{:, 11};
disk = dataArray{:, 12};
constraint = dataArray{:, 13};


